# Generated by Django 3.1.1 on 2020-09-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaopy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addrese',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=36),
        ),
    ]
