# Generated by Django 3.1.1 on 2020-09-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaopy', '0002_auto_20200928_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addrese',
            new_name='address',
        ),
    ]
