# Generated by Django 3.1.1 on 2020-09-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaopy', '0003_auto_20200928_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=False),
        ),
    ]
